[package]
name = "fast_poisson"
version = "0.1.0"
authors = ["Travis Veazey <travisvz@gmail.com>"]
edition = "2018"
description = "An implementation of Bridson's algorithm for fast Poisson disk sampling"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_xoshiro = "0.6.0"
