name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '30 5 * * 1' # 5:30 AM UTC on Mondays

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --all -- --check
  
  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: cargo clippy --all
  
  test:
    name: Tests
    needs: [rustfmt, clippy]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
        - 1.67.0 # MSRV
        - stable
        - beta
        features:
        - default
        - single_precision
        - derive_serde

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Install minimal ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test --verbose --features "${{ matrix.features }}"
